name: "Ruby on Rails CI"

env:
  RUBY_VERSION: 3.2.2
  NODE_VERSION: 19.4.0
  BUNDLER_VERSION: 2.4.12
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  rails-workflow:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${{ secrets.KEY }}
      GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
      GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SQLite
        run: sudo apt-get install -y libsqlite3-dev
        
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ env.RUBY_VERSION }}
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 19.4.0

      - name: Yarn Install
        run: yarn install
        
      - name: Set up database schema
        run: bin/rails db:migrate

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v3.0.1
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            ARGS: "-rlgoDzvc -i --delete"
            SOURCE: ""
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: ${{ secrets.TARGET }}
            EXCLUDE: "/dist/, /node_modules/"

      - name: Start server
        run: bundle exec rails s -p 3000 -b '0.0.0.0'
        
            