name: "Ruby on Rails CI"

env:
  RUBY_VERSION: 3.2.2
  NODE_VERSION: 19.4.0
  BUNDLER_VERSION: 2.4.12
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  rails-workflow:
    runs-on: ubuntu-latest
    env:
      GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
      GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
      RAILS_ENV: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SQLite
        run: sudo apt-get install -y libsqlite3-dev
        
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ env.RUBY_VERSION }}
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 19.4.0

      - name: Yarn Install
        run: yarn install
        
      - name: Set up database schema
        run: bin/rails db:migrate

      - name: Set up asset pipeline
        run: | 
          yarn build
          yarn build:css

      - name: Run tests
        run: bin/rake
        
      - name: Security Audit
        run: |
          gem install bundler-audit
          bundle-audit --update

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
            ARGS: "-rlgoDzvc -i --delete"
            SOURCE: ""
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: ${{ secrets.REMOTE_TARGET }}
            EXCLUDE: "/dist/, /node_modules/"